### ISSUE TITLE
New custom property for styling the dot

### ISSUE THREAD

**Issue by eszechet80** [Link2Twenty/l2t-paper-slider#9]
Hi!
It would be great to have a new property to customize the border and shadow of the slider dot (both selected and unselected). Right now we have "paper-slide-dot" and "paper-slide-dot-selected"

I use this component as an image slider, and the issue i have is that when the image has the color of one of the dots (i use black and white for the dots) in that part of the image, the dots become invisible. Using another color for the border would solve these cases because you'd either see the dot or the border.

Thanks!

**Comment by Link2Twenty** [comment]
Just so you know mixins are coming :+1: 

There were a few things for me to do (to make the style animation cope with them)

There's still a bug for me to iron out but it's close, here's a gif of my test build.

![mixinsdemo](https://cloud.githubusercontent.com/assets/3534427/17400227/a32b96ec-5a3e-11e6-8982-fd563d0e4e5e.gif)

**Comment by Link2Twenty** [comment]
OK, I think this is it in its final form.

Adding something like this to your styles.

``` CSS
l2t-paper-slider {
  --paper-slide-dot-styles: {
     width: 24px;
     height: 8px;
     margin: 6px;
     border-width: 4px; 
     border-style: inset; 
     border-color: #ccc;
     padding: 2px;
   }
}
```

And it will look like this.
![mixinfinal](https://cloud.githubusercontent.com/assets/3534427/17403315/15685d48-5a4f-11e6-9e39-fa063d9c40fe.gif)
